M48
; DRILL file {KiCad 8.0.4} date 2025-01-24T17:00:16-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-24T17:00:16-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0787
%
G90
G05
T1
X5.9437Y-3.8415
X5.9437Y-4.0325
T2
X6.063Y-3.8297
X6.063Y-4.0443
T3
X3.937Y-3.1496
X3.937Y-4.7244
X5.9055Y-3.1496
X5.9055Y-4.7244
M30
