# Form implementation generated from reading ui file '.\pump_frame.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(250, 110)
        GroupBox.setMinimumSize(QtCore.QSize(250, 110))
        GroupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout(GroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pump_label = QtWidgets.QLabel(parent=GroupBox)
        self.pump_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pump_label.setObjectName("pump_label")
        self.gridLayout.addWidget(self.pump_label, 0, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(parent=GroupBox)
        self.status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.power_button = QtWidgets.QPushButton(parent=GroupBox)
        self.power_button.setObjectName("power_button")
        self.horizontalLayout.addWidget(self.power_button)
        self.direction_button = QtWidgets.QPushButton(parent=GroupBox)
        self.direction_button.setObjectName("direction_button")
        self.horizontalLayout.addWidget(self.direction_button)
        self.edit_button = QtWidgets.QPushButton(parent=GroupBox)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setTitle(_translate("GroupBox", "Pump N/A"))
        self.pump_label.setText(_translate("GroupBox", "Power pin: N/A, Direction pin: N/A"))
        self.status_label.setText(_translate("GroupBox", "Power Status: N/A, Direction Status: N/A"))
        self.power_button.setText(_translate("GroupBox", "Power"))
        self.direction_button.setText(_translate("GroupBox", "Direction"))
        self.edit_button.setText(_translate("GroupBox", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroupBox = QtWidgets.QGroupBox()
    ui = Ui_GroupBox()
    ui.setupUi(GroupBox)
    GroupBox.show()
    sys.exit(app.exec())
